version: '3.4'

networks:
  web_net:
    external: true
  git_net:
    external: false

services:
  gitlab:
    image: gitlab/gitlab-ce:17.1.6-ce.0
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |

        ## Gitlab configs
        external_url 'https://git.andronymous.ir'
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = false
        nginx['listen_https'] = false
        nginx['custom_gitlab_server_config'] = "error_page 497 http://$$host:$$server_port$$request_uri;"
        gitlab_rails['gitlab_shell_ssh_port'] = 22

        ## Package Registry
        registry['enable'] = true
        registry_external_url 'https://reg.andronymous.ir'
        
        registry_nginx['listen_port'] = 5050
        registry_nginx['redirect_http_to_https'] = false
        registry_nginx['listen_https'] = false

        ## SSL configs
        nginx['ssl_certificate'] = "/ssl/etc/letsencrypt/live/git.andronymous.ir/fullchain.pem"
        nginx['ssl_certificate_key'] = "/ssl/etc/letsencrypt/live/git.andronymous.ir/privkey.pem"

        registry_nginx['ssl_certificate'] = "/ssl/etc/letsencrypt/live/git.andronymous.ir/fullchain.pem"
        registry_nginx['ssl_certificate_key'] = "/ssl/etc/letsencrypt/live/git.andronymous.ir/privkey.pem"
    ports:
      - '22:22'
      #- "443:433"
      #- "80:80"
      #- '5050:5050'
    volumes:
      - /data/gitlab-try/data/gitlab_backups:/var/opt/gitlab/backups
      - /data/gitlab-try/data/gitlab_data:/var/opt/gitlab
      - /data/gitlab-try/data/gitlab_logs:/var/log/gitlab
      - /data/gitlab-try/data/gitlab_config:/etc/gitlab
      - swag_conf:/ssl
    networks:
      git_net:
      web_net:


  gitlab-runner:
    image: gitlab/gitlab-runner:v17.3.1
    restart: always
    container_name: gitlab-runner
    volumes:
      - /data/gitlab-try/gitlab_runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
    networks:
      git_net:

volumes:
  swag_conf:
    external: true
