stages:
  - build
  - test
  - push
  - deploy

before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  stage: build
  script:
    - docker build --tag="$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME" .
  tags:
    - test2

test:
  stage: test
  script:
    - docker-compose run myapp python manage.py test

push:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME"

deploy:
  stage: deploy
  script:
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d
