---
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install nginx"
  apt:
    name: nginx
    state: present

- name: "Ensure vim is at the latest version"
  apt: name=vim state=latest