---

# 1. Basic File Transfer:
- name: Copy a file to the remote host
  copy:
    src: /data/file.txt
    dest: /data/file.txt

# 2. Advanced File Transfer:
- name: Copy a file and set permissions and ownership
  copy:
    src: /data/file.txt
    dest: /data/file.txt
    owner: myuser
    group: mygroup
    mode: '0644' # or use preserve to transfer the exact source (src) permissions
    backup: yes

# 3. Copying a Directory:
- name: Copy /data directory to remote /data directory
  copy:
    src: /data
    dest: /
    recursive: yes

# 4. create a file with content of another file:
- name: Create a file with content
  copy:
    dest: /data/sample-script.sh
    content: "cat /etc/passwd"
    mode: '0755'

# 5. Basic File Transfer for apt proxy:
- name: Copy socks5 config for apt
  copy:
    src: 95proxies
    dest: /etc/apt/apt.conf.d/95proxies
    force: yes

- name: Copy http proxy for apt
  copy:
    src: proxy.conf
    dest: /etc/apt/apt.conf.d/proxy.conf
    force: yes
