version: '3.2'

services:

  nginx1:
    image: nginx
    container_name: proxy
    restart: unless-stopped
    volumes:
      - nginx_conf:/etc/nginx
      - nginx_files:/var/www/nginx
      - nginx_logs:/var/log/nginx
      - /etc/letsencrypt:/etc/nginx/ssl
    ports:
      - '80:80'
    networks:
      web_net:

volumes:
  nginx_conf:
    external: true
  nginx_files:
    external: true
  nginx_logs:
    external: true

networks:
  web_net:
    external: true



