global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'prometheus'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['188.121.110.34:9093']

rule_files:
  - "/etc/prometheus/*.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['188.121.110.34:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.121.110.34:8080']